//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waBiblioteca
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LIBRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIBRO()
        {
            this.LOG_LIBRO = new HashSet<LOG_LIBRO>();
        }
        [Display(Name = "Correlativo")]
        public int IDD_LIBRO { get; set; }
        [Display(Name = "Libro")]
        public string NOM_LIBRO { get; set; }
        [Display(Name = "Editor")]
        public string NOM_EDITO { get; set; }
        [Display(Name = "Autor")]
        public string NOM_AUTOR { get; set; }
        [Display(Name = "Idioma")]
        public string NOM_IDIOM { get; set; }
        [Display(Name = "# Páginas")]
        public Nullable<int> NUM_PAGIN { get; set; }
        [Display(Name = "Resumen")]
        public string DES_RESUM { get; set; }
        [Display(Name = "Categoria")]
        public Nullable<int> IDD_CATER { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_LIBRO> LOG_LIBRO { get; set; }
    }
}
