//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waBiblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_LIBRO
    {
        public int IDD_LOG_LIBRO { get; set; }
        public Nullable<int> IDD_LIBRO { get; set; }
        public Nullable<int> IDD_USUAR { get; set; }
    
        public virtual LIBRO LIBRO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
