//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waBiblioteca
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DS2_BIBLIOTECAEntities : DbContext
    {
        public DS2_BIBLIOTECAEntities()
            : base("name=DS2_BIBLIOTECAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIA> CATEGORIA { get; set; }
        public virtual DbSet<LIBRO> LIBRO { get; set; }
        public virtual DbSet<LOG_LIBRO> LOG_LIBRO { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<RUTA_LIBRO> RUTA_LIBRO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
