//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waBiblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUTA_LIBRO
    {
        public int IDD_RUTA_LIBRO { get; set; }
        public string NOM_RUTA { get; set; }
        public string NOM_ARCHI { get; set; }
        public string NOM_ARCHI_FISIC { get; set; }
        public Nullable<int> IDD_LIBRO { get; set; }
    }
}
