//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waBiblioteca
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.LOG_LIBRO = new HashSet<LOG_LIBRO>();
        }
        [Display(Name = "Correlativo")]
        public int IDD_USUAR { get; set; }
        [Display(Name = "Nombre")]
        public string NOM_USUAR { get; set; }
        [Display(Name = "Apellido")]
        public string APE_USUAR { get; set; }
        [Display(Name = "Tipo de Documento")]
        public string TIP_DOCUM { get; set; }
        [Display(Name = "# Documento")]
        public string NUM_DOCUM { get; set; }
        [Display(Name = "Email")]
        public string NOM_CORRE { get; set; }
        [Display(Name = "Contraseña")]
        public string DES_CONTR { get; set; }
        [Display(Name = "Rol")]
        public Nullable<int> IDD_ROL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_LIBRO> LOG_LIBRO { get; set; }
        public virtual ROL ROL { get; set; }
    }
}
